HomeWork2/Prob6/Prob6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hotel/', include('hotel.urls'))
]

HomeWork2/Prob6/hotel/urls.py
from django.urls import path
from . import views

app_name = 'hotel'

# TODO 添加urlpattern
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('regeister/', views.CustomerRegisterView.as_view(), name='register'),
    path('leave/', views.CustomerLogOutView.as_view(), name='leave'),
    path('manage/', views.RoomManageView.as_view(), name='manage')
]

HomeWork2/Prob6/hotel/models.py
from django.db import models

# Create your models here.

from datetime import datetime


class Customer(models.Model):
    gender_choice = (
        ("男", "男"),
        ("女", "女")
    )

    customerName = models.CharField(max_length=30, verbose_name="旅客姓名")

    customerGender = models.CharField(max_length=5, verbose_name="性别", choices=gender_choice)

    customerId = models.CharField(max_length=18, primary_key=True, verbose_name="旅客身份证号码")

    customerPhoneNumber = models.CharField(max_length=11,verbose_name="手机号码")

    roomId = models.CharField(max_length=10, verbose_name="房间号")

    roomtype = (
        ("大床房", "大床房"),
        ("标间", "标间"),
        ("钟点房", "钟点房")
    )

    roomType = models.CharField(max_length=8, verbose_name="房间类型", choices=roomtype)

    customerCheckInTime = models.DateTimeField(default=datetime.now, verbose_name="入住时间")

    customerStayTime = models.IntegerField(verbose_name="入住时长")

HomeWork2/Prob6/hotel/forms.py
from django import forms


class RegisterForm(forms.Form):
    customerName = forms.CharField(max_length=30)
    customerId = forms.CharField(max_length=5, min_length=5)
    customerGender = forms.CharField(max_length=5)
    customerStayTime = forms.IntegerField()
    customerPhoneNumber = forms.CharField(max_length=11,min_length=11)
    roomType = forms.CharField(max_length=8)


class LeaveForm(forms.Form):
    customerName = forms.CharField(max_length=30)
    customerId = forms.CharField(max_length=5, min_length=5)

HomeWork2/Prob6/hotel/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic.base import View

from . import forms
from . import models


class IndexView(View):
    def get(self, request):
        return render(request, 'hotel/index.html')


class CustomerRegisterView(View):
    def get(self, request):
        return render(request, 'hotel/register.html', )

    def post(self, request):
        register_form = forms.RegisterForm(request.POST)
        if register_form.is_valid():
            customerId = register_form.cleaned_data['customerId']
            if not models.Customer.objects.filter(customerId=customerId).exists():
                customerName = register_form.cleaned_data['customerName']
                customerGender = register_form.cleaned_data['customerGender']
                customerStayTime = register_form.cleaned_data['customerStayTime']
                roomType = register_form.cleaned_data['roomType']
                customerPhoneNumber = register_form.cleaned_data['customerPhoneNumber']
                Customer = models.Customer(customerId=customerId, customerName=customerName,
                                           customerGender=customerGender,
                                           customerStayTime=customerStayTime, roomType=roomType,
                                           customerPhoneNumber=customerPhoneNumber)
                Customer.save()
                return render(request, 'hotel/register.html', {'success': True, 'msg': '登记成功'})
            else:
                return render(request, 'hotel/register.html', {'error': True, 'msg': '该旅客已住店，请先删除该旅客信息'})
        else:
            return render(request, 'hotel/register.html', {'error': True, 'msg': '输入信息不合法'})


class CustomerLogOutView(View):
    def get(self, request):
        return render(request, 'hotel/leave.html')

    def post(self, request):
        leave_form = forms.LeaveForm(request.POST)
        if leave_form.is_valid():
            customerId = leave_form.cleaned_data['customerId']
            if models.Customer.objects.filter(customerId=customerId).exists():
                customerName = leave_form.cleaned_data['customerName']
                if customerName != models.Customer.objects.get(customerId=customerId).customerName:
                    return render(request, 'hotel/leave.html', {'error': True, 'msg': '旅客信息不匹配'})
                else:
                    models.Customer.objects.get(customerId=customerId).delete()
                    return render(request, 'hotel/leave.html', {'success': True, 'msg': '删除成功'})
            else:
                return render(request, 'hotel/leave.html', {'error': True, 'msg': '该旅客不存在'})
        else:
            return render(request, 'hotel/leave.html', {'error': True, 'msg': '输入信息不合法'})


class RoomManageView(View):
    def get(self, request):
        customerInfo = models.Customer.objects.all()
        print(type(customerInfo))
        return render(request, 'hotel/manage.html', {"customerInfo": customerInfo})

HomeWork2/Prob6/hotel/templates/hotel/index.html
{% extends 'base.html' %}

{% block title %}酒店管理系统{% endblock %}

{% load static %}

{% block private_work %}
    <div class="container text-center" style="margin-top: 100px">
        <h1>欢迎使用此酒店管理系统</h1>
        <div class="row" style="margin-top: 50px">
            <div class="col-4">
                <a class="btn btn-success btn-lg" href="{% url 'hotel:register' %}">旅客登记</a>
            </div>
            <div class="col-4">
                <a class="btn btn-info btn-lg" href="{% url 'hotel:leave' %}">旅客离开</a>
            </div>
            <div class="col-4">
                <a class="btn btn-primary btn-lg" href="{% url 'hotel:manage' %}">房间管理</a>
            </div>
        </div>
    </div>
{% endblock %}

HomeWork2/Prob6/hotel/templates/hotel/leave.html
{% extends 'base.html' %}\

{% block title %}旅客离开{% endblock %}

{% load static %}

{% block private_work %}
    <div class="container " style="margin-top: 80px">
        <div class="text-center">
            <h2>旅客离开</h2>
            <p class="lead">请确认欲离开旅客的信息</p>
        </div>
        <div style="width: 600px;margin: 0 auto">
            <form method="post">
                {% csrf_token %}
                <div class="form-group row">
                    <label for="inputname" class="col-3 col-form-label">旅客姓名</label>
                    <div class="col-9">
                        <input type="text" class="form-control" id="inputname" placeholder="请输入姓名" name="customerName">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputidcard" class="col-3 col-form-label">旅客证件</label>
                    <div class="col-9">
                        <input type="text" class="form-control" id="inputidcard" placeholder="请输入证件号" name="customerId">
                    </div>
                </div>
                <div class="row">
                    <label class="col-3"></label>
                    <div class="col-9">
                        {% if error %}
                            <div class="alert alert-danger" role="alert">
                                {{ msg }}
                            </div>
                        {% endif %}
                        {% if success %}
                            <div class="alert alert-success" role="alert">
                                {{ msg }}
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-3"></label>
                    <div class="col-9">
                        <button class="btn btn-secondary btn-lg" type="submit">确认</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

HomeWork2/Prob6/hotel/templates/hotel/manage.html
{% extends 'base.html' %}

{% load static %}

{% block title %}房间信息管理{% endblock %}

{% block private_work %}
    <div class="container " style="margin-top: 80px">
        <div class="text-center">
            <h2>房间信息管理</h2>
            <p class="lead">当前房间入住情况</p>
        </div>
        <div style="width: 1000px;margin: 0 auto">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">客人姓名</th>
                    <th scope="col">客人性别</th>
                    <th scope="col">手机号</th>
                    <th scope="col">客人证件号</th>
                    <th scope="col">房间类型</th>
                    <th scope="col">入住时间</th>
                    <th scope="col">入住时长</th>
                </tr>
                </thead>
                <tbody>
                {% for customer in customerInfo %}
                    <tr>
                        <th>{{ customer.customerName }}</th>
                        <td>{{ customer.customerGender }}</td>
                        <td>{{ customer.customerPhoneNumber }}</td>
                        <td>{{ customer.customerId }}</td>
                        <td>{{ customer.roomType }}</td>
                        <td>{{ customer.customerCheckInTime }}</td>
                        <td>{{ customer.customerStayTime }}天</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

HomeWork2/Prob6/hotel/templates/hotel/register.html
{% extends 'base.html' %}

{% block title %}旅客登记{% endblock %}

{% load static %}

{% block private_work %}
    <div class="container" style="margin-top: 80px">
        <div class="text-center">
            <h2>旅客登记</h2>
            <p class="lead">请填写以下信息已完成旅客入住登记</p>
        </div>
        <div style="width: 600px;margin: 0 auto">
            <form method="post">
                {% csrf_token %}
                <div class="form-group row">
                    <label for="inputname" class="col-3 col-form-label">旅客姓名</label>
                    <div class="col-9">
                        <input type="text" class="form-control" id="inputname" placeholder="请输入姓名" name="customerName">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputidcard" class="col-3 col-form-label">旅客证件</label>
                    <div class="col-9">
                        <input type="text" class="form-control" id="inputidcard" placeholder="请输入证件号" name="customerId">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputphone" class="col-3 col-form-label">旅客手机号</label>
                    <div class="col-9">
                        <input type="text" class="form-control" id="inputphone" placeholder="请输入手机号码" name="customerPhoneNumber">
                    </div>
                </div>
                <fieldset class="form-group">
                    <div class="row">
                        <legend class="col-form-label col-3">旅客性别</legend>
                        <div class="col-9">
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="customerGender" id="genderman"
                                       value="男" checked>
                                <label class="form-check-label" for="genderman">
                                    男
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="customerGender" id="genderwoman"
                                       value="女">
                                <label class="form-check-label" for="genderwoman">
                                    女
                                </label>
                            </div>
                        </div>
                    </div>
                </fieldset>
                <fieldset class="form-group">
                    <div class="row">
                        <legend class="col-form-label col-3">房间类型</legend>
                        <div class="col-9">
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="roomType" id="Big"
                                       value="大床房" checked>
                                <label class="form-check-label" for="big">
                                    大床房
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="roomType" id="Stardard"
                                       value="标间">
                                <label class="form-check-label" for="Stardard">
                                    标间
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="roomType" id="Small"
                                       value="钟点房">
                                <label class="form-check-label" for="Small">
                                    钟点房
                                </label>
                            </div>
                        </div>
                    </div>
                </fieldset>
                <div class="form-group row">
                    <label for="inputday" class="col-3 col-form-label">入住时长</label>
                    <div class="col-9">
                        <input type="text" class="form-control" id="inputday" placeholder="请输入入住几天"
                               name="customerStayTime">
                    </div>
                </div>
                <div class="row">
                    <label class="col-3"></label>
                    <div class="col-9">
                        {% if error %}
                            <div class="alert alert-danger" role="alert">
                                {{ msg }}
                            </div>
                        {% endif %}
                        {% if success %}
                            <div class="alert alert-success" role="alert">
                                {{ msg }}
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-3"></label>
                    <div class="col-9">
                        <button class="btn btn-primary btn-lg" type="submit">提交</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

HomeWork2/Prob6/templates/base.html
<!DOCTYPE html>
<html lang="zh_cn">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static '/public_css/bootstrap.min.css' %}">
    {% block private_css %}
    {% endblock %}
    <title>{% block title %}Title{% endblock %}</title>
</head>
<body>
<div>
    <a class="btn-secondary" href="{% url 'hotel:index' %}">首页</a>
    {% block private_work %}

    {% endblock %}
</div>
</body>
<script src="{% static '/public_js/jquery.slim.min.js' %}"></script>
<script src="{% static '/public_js/popper.min.js' %}"></script>
<script src="{% static '/public_js/bootstrap.min.js' %}"></script>
</html>